spring:
  jpa:
    open-in-view: false #EntityManager in view 옵션 끔 서비스계층에서만 동작, 컨트롤러 계층에서는 작동하지 않는다.
    generate-ddl: 'false' #애플리케이션이 실행될 때 데이터베이스 스키마(DDL)를 생성하지 않도록 한다.
    hibernate:
      ddl-auto: none #Hibernate가 데이터베이스 스키마를 자동으로 관리하지 않음을 설정한다.
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        #Hibernate가 테이블과 컬럼 이름의 네이밍 전략을 표준 구현체로 설정 jpa 엔티티 클래스와 데이터베이스 테이블/컬럼의 이름 매핑 방식 정의
    properties:
      hibernate:
        format_sql: 'true' #Hibernate가 생성하는 SQL 쿼리 출력
    show-sql: 'true' #SQL 쿼리 콘솔 출력
  datasource:
    password: ${spring.db.password}
    url: ${spring.db.url}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${spring.db.username}